// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { batch } from "./batch.js";
import { create } from "./create.js";
import { findEdge } from "./findEdge.js";
import { findEdges } from "./findEdges.js";
import { findNeighbor } from "./findNeighbor.js";
import { findNeighbors } from "./findNeighbors.js";
import { findNode } from "./findNode.js";
import { findNodes } from "./findNodes.js";
import { forEachEdge } from "./forEachEdge.js";
import { forEachNeighbor } from "./forEachNeighbor.js";
import { forEachNode } from "./forEachNode.js";
import { fromJS } from "./fromJS.js";
import { getEdge } from "./getEdge.js";
import { getEdges } from "./getEdges.js";
import { getNeighbor } from "./getNeighbor.js";
import { getNeighbors } from "./getNeighbors.js";
import { getNode } from "./getNode.js";
import { getNodes } from "./getNodes.js";
import { hasEdge } from "./hasEdge.js";
import { hasNode } from "./hasNode.js";
import { mapEdge } from "./mapEdge.js";
import { mapNode } from "./mapNode.js";
import { mergeEdge } from "./mergeEdge.js";
import { mergeNode } from "./mergeNode.js";
import { removeEdge } from "./removeEdge.js";
import { removeNode } from "./removeNode.js";
import { setEdge } from "./setEdge.js";
import { setNode } from "./setNode.js";
import { toJS } from "./toJS.js";

type NodeId = PropertyKey

type Node = { id: NodeId, type: string }

type NodeType<T extends Node> = T["type"]

type NodeOfType<T extends Node, U extends NodeType<T>> = Extract<T, { type: U }>

type NodeIdentifier<T extends Node, U = NodeType<T>> =
    | { id: Extract<T, { type: U }>["id"], type: U }
    | [U, id: Extract<T, { type: U }>["id"]]

type Edge = Record<string, unknown> | void

type Edges<N extends Node> = Partial<Record<NodeType<N>, Partial<Record<NodeType<N>, Edge>>>>

type SourceTypesMap = ReadonlyMap<any, SourceIdsMap>

type SourceIdsMap = ReadonlyMap<NodeId, TargetTypesMap>

type TargetTypesMap = ReadonlyMap<any, TargetIdsMap>

type TargetIdsMap = ReadonlyMap<NodeId, Edge>

type NodeIdsMap<T extends Node, U extends NodeType<T> = NodeType<T>> = ReadonlyMap<NodeId, NodeOfType<T, U>>

interface NodeTypesMap<T extends Node> extends ReadonlyMap<NodeType<T>, NodeIdsMap<T, NodeType<T>>> {
    get: <V extends NodeType<T>>(type: V) => NodeIdsMap<T, V> | undefined
}

interface Graph<N extends Node, _E extends Edges<N>> extends Map<"nodes" | "edges" | "clones", NodeTypesMap<N> | SourceTypesMap | Set<any>> {
    delete: (key: "clones") => boolean
    get: ((key: "nodes") => NodeTypesMap<N> | undefined) & ((key: "edges") => SourceTypesMap | undefined) & ((key: "clones") => Set<any> | undefined)
    set: (key: "clones", value: Set<any>) => this
}

declare namespace Graph {
    export {
        batch,
        create,
        findEdge,
        findEdges,
        findNeighbor,
        findNeighbors,
        findNode,
        findNodes,
        forEachEdge,
        forEachNeighbor,
        forEachNode,
        fromJS,
        getEdge,
        getEdges,
        getNeighbor,
        getNeighbors,
        getNode,
        getNodes,
        hasEdge,
        hasNode,
        mapEdge,
        mapNode,
        mergeEdge,
        mergeNode,
        removeEdge,
        removeNode,
        setEdge,
        setNode,
        toJS,
    }
}

export {
    Graph,
    Edge,
    Edges,
    Node,
    NodeId,
    NodeIdentifier,
    NodeIdsMap,
    NodeOfType,
    NodeType,
    NodeTypesMap,
    SourceIdsMap,
    SourceTypesMap,
    TargetIdsMap,
    TargetTypesMap,
}
