// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { batch } from "./batch.js";
import { create } from "./create.js";
import { findEdge } from "./findEdge.js";
import { findEdges } from "./findEdges.js";
import { findNeighbor } from "./findNeighbor.js";
import { findNeighbors } from "./findNeighbors.js";
import { findNode } from "./findNode.js";
import { findNodes } from "./findNodes.js";
import { forEachEdge } from "./forEachEdge.js";
import { forEachNeighbor } from "./forEachNeighbor.js";
import { forEachNode } from "./forEachNode.js";
import { fromJS } from "./fromJS.js";
import { getEdge } from "./getEdge.js";
import { getEdges } from "./getEdges.js";
import { getNeighbor } from "./getNeighbor.js";
import { getNeighbors } from "./getNeighbors.js";
import { getNode } from "./getNode.js";
import { getNodes } from "./getNodes.js";
import { hasEdge } from "./hasEdge.js";
import { hasNode } from "./hasNode.js";
import { mapEdge } from "./mapEdge.js";
import { mapNode } from "./mapNode.js";
import { mergeEdge } from "./mergeEdge.js";
import { mergeNode } from "./mergeNode.js";
import { removeEdge } from "./removeEdge.js";
import { removeNode } from "./removeNode.js";
import { setEdge } from "./setEdge.js";
import { setNode } from "./setNode.js";
import { toJS } from "./toJS.js";

export const Graph = {
    batch,
    create,
    findEdge,
    findEdges,
    findNeighbor,
    findNeighbors,
    findNode,
    findNodes,
    forEachEdge,
    forEachNeighbor,
    forEachNode,
    fromJS,
    getEdge,
    getEdges,
    getNeighbor,
    getNeighbors,
    getNode,
    getNodes,
    hasEdge,
    hasNode,
    mapEdge,
    mapNode,
    mergeEdge,
    mergeNode,
    removeEdge,
    removeNode,
    setEdge,
    setNode,
    toJS,
}
